# Create a new post
POST http://localhost:3000/post/
Content-Type: application/json

{
  "content": "This is a new post from request file",
  "senderId": "12345"
}

###

# Get all posts
GET http://localhost:3000/post/

###


# Get a post by ID
GET http://localhost:3000/post/677ebd7513b7eb6e9a076ebc

###

# Get a post by sender ID
GET http://localhost:3000/post?sender=12345

###

# Update a post by ID
PUT http://localhost:3000/post/677ebd7513b7eb6e9a076ebc
Content-Type: application/json

{
  "content": "Updated content of the post",
  "senderId": "12345"
}

###

# Create a new comment
POST http://localhost:3000/comment/
Content-Type: application/json

{
  "content": "This is a new comment",
  "senderId": "67890",
  "postId": "677ebd7513b7eb6e9a076ebc"
}

###

# Update a comment by ID
PUT http://localhost:3000/comment/677ebdb813b7eb6e9a076ec3
Content-Type: application/json

{
  "content": "Updated comment contenttttttttttttttttttt",
  "senderId": "67890"
}

###

# Get all comments
GET http://localhost:3000/comment/

###

# Get comments by post ID
GET http://localhost:3000/comment/post?postId=677ebd7513b7eb6e9a076ebc

###

# Delete a comment by ID
DELETE http://localhost:3000/comment/677ebdb813b7eb6e9a076ec3
